### ISSUE TITLE
Fix do_sync command's JSON-compatibility in the result

### ISSUE THREAD

**Issue by AArnott** [zingolabs/zingolib#463]
#447 changed a JSON string to a more human readable string in response to the commands.rs `do_sync` command. This makes consuming it from a javascript wallet more difficult.

Per @zancas' suggestion, the new strongly-typed struct should implement a trait that makes it readily convertible to a JSON string to bring back the convenient access from javascript.

**Comment by juanky201271** [comment]
The problem here is that zingo-mobile consume a lot of commands from zingo-lib, the result of this commands is not only for humans... please take this in mind in the future, and please would be really useful if you could revert from string to a `pretty` ASAP because zingo-mobile is not working this way, thanks for your help.

And I think the humans that works with zingo-cli can perfectly understand a JSON result.

For more info: All the commands in zingolib works the same way: on error the result is a string like this: `Error: xxxxxxxxx` and if the command doean't have any errors, the result is always a `string` which you can parse as a JSON. Please don't change this behavior randomly...

**Comment by juanky201271** [comment]
@zancas I'm happy to change everything... if you want to change how the commands work, It's fine to me, but please let's coordinate a bit how & what will be the result...

**Comment by AArnott** [comment]
Sorry for the disruption. I was not aware of the patterns and usage of the CLI commands. I'm happy to honor them going forward and will work to address the regression ASAP.

**Comment by juanky201271** [comment]
> Sorry for the disruption. I was not aware of the patterns and usage of the CLI commands. I'm happy to honor them going forward and will work to address the regression ASAP.

Thanks so much.

**Comment by zancas** [comment]
I approved this regression, without enough thought.   This was my mistake.   Going forward we want strong-types that convert to correctly-formatted-Strings ergonomically.    We can have our cake and eat it too.   My apologies for not making this a seemless upgrade.
