### ISSUE TITLE
Regtest mode generated blocks don't show up

### ISSUE THREAD

**Issue by AloeareV** [zingolabs/zingolib#71]
When I run in regtest mode, I get 
```
zcashd is starting in regtest mode, please standby...
zcashd start section completed, zcashd should be running.
lightwalletd is about to start. This should only take a moment.
lightwalletd is now started in regtest mode, please standby...
lwd start section completed, lightwalletd should be running!
Standby, Zingo-cli should be running in regtest mode momentarily...
regtest detected and network set correctly!
Creating a new wallet
Lightclient connecting to http://127.0.0.1:9067/
Error with response: Status { code: Unknown, message: "Cache is empty. Server is probably not yet ready", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }
Ready!
```
After using `zcash-cli` to generate blocks, those blocks never show up on the zingo-cli, even after running `rescan`.

**Comment by zancas** [comment]
This is a significant UnknownUnknown.    Why does this occur?

The first thing to do, is to monitor the local block cache, specific to this regtest mode.

I believe it's here:

`regtest/data/zcashd/regtest/`

While `watch 'ls -la'` that directory, launch the _same_ `zcashd`,

(located here: `regtest/bin/zcashd`) (in regtest mode with the appropriate "datadir")

Attach `regtest/bin/zcash-cli` to _THAT_ zcashd, and report the output of:

  1. `zcash-cli getinfo`
  2. `zcash-cli getblockchaininfo`
  3. `zcash-cli version`

in this comment thread.

Can we generate _THIS_ error "directly" with `zcash-cli`:

`Error with response: Status { code: Unknown, message: "cache is empty, server is probably not yet ready", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }`

NO..  because @AloeareV tells me that it's a `lightwalletd` error.  ;)

Now with this context:

  0. use `tail -F regtest/logs/lightwalletd/stdout.log`
       * spend some time studying this log output (which is probably old-or-empty prior to step 1)
  1. launch `zingo-cli --regtest`   Use explicit flags `--data-dir` and `--server`directories to guarantee that the same data is being referenced, as the ones we set up above.
       * notice that the `tail` of the lightwalletd log receiving data!
   2. observe that we get the `lightwalletd` error (or don't)!!! in the `zingo-cli` output
   3a. invoke `zcash-cli generate 1` and watch the `lightwalletd` `tail` to see what happens
   3b. invoke relevant `zingo-cli` commands to see what happens in the `tail`

Objective:   Understand the root cause of the `ligthwalletd` error message reporting an empty cache to the `zingo-cli` user.

Completion Criteria:
    * the error source is understood and explained
    * a test in zingo-cli WHERE? that:
          i.   generates the error
          ii.  makes assertions about it
          iii. fails in the current state
    * a fix that for the error cause that:
          i.   is stable <-- works every time
          ii.  automatic  <-- no user intervention
          iii. proven <--  makes the test pass

**Comment by dannasessha** [comment]
ACK! I can just say off the top of my head that when I would run regtest mode with a previously unused datadir, I created blocks with `zcash-cli` and then got `zingo-cli` to recognize them, though I might have restarted. It's been a little while. I'll start looking into this soon, thank you for the issue.

**Comment by dannasessha** [comment]
Some problems seemed to come up around #69 and #70 that I don't think are yet resolved.

Is there any plan for @zancas or @AloeareV to address that subject? Is there something I should know that would lead me to directly work on this issue before trying to reconcile issues from the prior merge/close?

**Comment by AloeareV** [comment]
> Some problems seemed to come up around #69 and #70 that I don't think are yet resolved.
> 
> Is there any plan for @zancas or @AloeareV to address that subject? Is there something I should know that would lead me to directly work on this issue before trying to reconcile issues from the prior merge/close?

I don't remember which problems you're referring to. We don't seem to have talked about them or linked to issues about them from those PRs directly.

**Comment by dannasessha** [comment]
After submitting PR #74 I am also seeing this issue, which makes sense because it based on `dev`.

I haven't tested to see if this issue also appears on the now-closed PR #69 branch.

**Comment by dannasessha** [comment]
I am not seeing this issue (printed in the stdout with regtest mode) on commit `c96b886` (now in the lineage of `dev`) or on `093ba2` (orphaned by #69). Thus it seemes to have been introduced by the merge of #70. 

My next question would probably be about what functionality was added in #70... I'll look into that.

**Comment by dannasessha** [comment]
> Can we generate _THIS_ error "directly" with `zcash-cli`:
> 
> `Error with response: Status { code: Unknown, message: "cache is empty, server is probably not yet ready", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }`
> 
> NO.. because @AloeareV tells me that it's a `lightwalletd` error. ;)

I'm not certain if we can generate it with `zcash-cli` yet, but I don't think this it's a lightwalletd error. I'm almost sure it's from `zingolib` in fact.

On #74 I added a `stderr` log file, and I have satisfied myself at least.

**Comment by dannasessha** [comment]
```
.../lightwalletd: 0 $
grep -nr "probably not"
...
frontend/frontend_test.go:175:	if err.Error() != "cache is empty, server is probably not yet ready" {
frontend/service.go:68:		return nil, errors.New("cache is empty, server is probably not yet ready")
frontend/service.go:243:		return nil, errors.New("Cache is empty. Server is probably not yet ready")
```

**Comment by dannasessha** [comment]
So this error does seem to be from lightwalletd, but is not reported in its stdout or its stderr. It should be one of the first two errors, because of the lack of capitalization of `cache`. 

I have reproduced this behavior with various numbers of blocks in the data directory.

It's odd to me that the current `dev` branch produces this error while previous version didn't, but I can't account for it yet. Because the error's origin is in `go` - that might slow me down.. I could either trace through the existing code (which I have inferred is the preferred way to proceed) or I could try to isolate the change that produced this error (which I began to do but didn't finalize).

**Comment by dannasessha** [comment]
here is the relevant code from `lightwalletd/frontend/service.go` 
```
/ GetLatestBlock returns the height of the best chain, according to zcashd.
    61 func (s *lwdStreamer) GetLatestBlock(ctx context.Context, placeholder *walletrpc.ChainSpec) (*walletrpc.BlockID, error) {
    62     // Lock to ensure we return consistent height and hash
    63     s.mutex.Lock()
    64     defer s.mutex.Unlock()
    65     latestBlock := s.cache.GetLatestHeight()
    66
    67     if latestBlock == -1 {
    68         return nil, errors.New("cache is empty, server is probably not yet ready")
    69     }
    70     latestHash := s.cache.GetLatestHash()
    71
    72     return &walletrpc.BlockID{Height: uint64(latestBlock), Hash: latestHash}, nil
    73 }
```
I'm not clear on the `(s *lwdStreamer)` bit on line 61...

... besides this I have one other idea I want to pursue...

**Comment by zancas** [comment]
What's the current hypothesis that might explain this issue?

**Comment by dannasessha** [comment]
Right now I think it's because of separating the datadirs between zcashd and lightwalletd. By simply changing them in the newest commits to try to share a directory, I didn't suppress the warning, so if it is that, it needs to be understood better, but that still what I think is going on if I had to bet on it.

**Comment by dannasessha** [comment]
Okay, after more experimentation, I am revising my answer. The commits on which I was previously able to run `zingo-cli` without this error are now also experiencing it.

So what has changed? `lightwalletd` has remained constant, but `zcashd` itself has had more commits.

I've already been not using the most recent commit on `master` due to it not building on my development machine, and settling for `Zcash version v5.2.0-df6e05173` instead. I think it's possible that an update to `zcashd` itself might be causing the issue, and I did not recognize this because I had been running `zingo-cli` with datadirs that already had generated block in it.

Now I can (on newer as well as older 'previously known to me to be working' commits) start `zingo-cli`, and this error appears. I cannot add blocks that are recognized to `zingo-cli` by using `zcash-cli` to generate the blocks, though `zcash-cli` reports the creation of the blocks; therefore I believe it is succeeding in commanding `zcashd`. I'll try to see if these blocks are changing the datadir directories at all. If they are, then I am beginning to suspect that `lightwalletd` is not able to communicate correctly with `zcashd` anymore. I could also experiment by using older versions of `zcashd` (maybe, the last release) to see if I can get that to perform how I expect.

**Comment by dannasessha** [comment]
Okay now I really don't know. I can produce the error with a range of `zcashd` builds (I tried the last few releases) as well as `zingolib` builds. I've kept `lightwalletd` at `2d3943` which has been the master (and the last release) since July 21.

Maybe a backing library change?
